apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: astartevoyageringresses.api.astarte-platform.org
spec:
  group: api.astarte-platform.org
  names:
    kind: AstarteVoyagerIngress
    listKind: AstarteVoyagerIngressList
    plural: astartevoyageringresses
    singular: astartevoyageringress
    shortNames:
    - avi
    - astartevi
    categories:
    - all
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
